# Generated by Django 5.2.4 on 2025-07-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugasakhir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugasakhir',
            name='proposal',
            field=models.FileField(blank=True, null=True, upload_to='proposals/'),
        ),
    ]
