# Generated by Django 5.2.4 on 2025-07-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugasakhir', '0003_bimbingan_nilai_penguji_proposal_seminar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimbingan',
            name='status',
            field=models.CharField(default='diajukan', max_length=50),
        ),
        migrations.AlterField(
            model_name='bimbingan',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(default='diajukan', max_length=50),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='status',
            field=models.CharField(default='menunggu', max_length=50),
        ),
    ]
